---
- name: add overlay cvut
  layman: >
    name=cvut
    list_url=http://raw.github.com/cvut/gentoo-overlay/master/overlay.xml

- name: 'install nss_ldap, pam_ldap and ssh-ldap-pubkey'
  portage: package={{ item }}
  with_items:
    - sys-auth/nss_ldap
    - sys-auth/pam_ldap
    - sys-auth/ssh-ldap-pubkey

- name: install unscd
  portage: package=sys-apps/unscd
  when: sysauth_ldap_unscd_enabled

- name: remove useless example files
  file: >
    path=/etc/nsswitch.ldap
    state=absent
  tags: cleanup

- name: copy useradd-nis and userdel-nis scripts
  copy: >
    src={{ item }}
    dest=/usr/local/bin/{{ item }}
    owner=root group=root mode=0744
  with_items:
    - useradd-nis
    - userdel-nis
